### ISSUE TITLE
GitHub Docs

### ISSUE THREAD

**Issue by CoolCoder353** [KablammoMan/Img2DFT#1]
You should feature this program on a GitHub doc page so people can seer and run your code without having to install it.****

**Comment by KablammoMan** [comment]
How do I do that? I've only ever used GitHub for storing the source for my applications, never to make Github run the application.

**Comment by CoolCoder353** [comment]
https://docs.github.com/en/pages

**Comment by KablammoMan** [comment]
Ok, I'll have a look into that and close the issue once I get it set up.

**Comment by KablammoMan** [comment]
Its live at https://kablammoman.github.io/Img2DFT/!
